### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by ghost** [iiFlamiinBlaze/BlazinJoin#1]
The plugin does not display title, subtitle and messages when joining and curse.

**Comment by Xalinova** [comment]
Same

**Comment by iiFlamiinBlaze** [comment]
I will look into it

**Comment by iiFlamiinBlaze** [comment]
Any errors at all?

**Comment by Xalinova** [comment]
No errors seen in console, just not appearing at all.

**Comment by iiFlamiinBlaze** [comment]
Can you send me the config file?

**Comment by Xalinova** [comment]
<img width="767" alt="screen shot 2018-07-04 at 11 22 25 pm" src="https://user-images.githubusercontent.com/40827689/42279461-2fc18566-7fe1-11e8-9720-a417d13c0035.png">

**Comment by iiFlamiinBlaze** [comment]
K I will look into it
